### ISSUE TITLE
[1.12.2] Compatibility Issue: NoClassDefFoundError for ItemHDPE$PlasticItem with Tinkers‘ Evolution

### ISSUE THREAD

**Issue by zlf9790** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#153]
My Minecraft 1.12.2 modpack crashes during initialization when both Mekanism-CE-Unofficial-All-9.9.2.237 and Tinkers‘ Evolution (tconevo-1.12.2-1.1.1) are present. The crash occurs because Tinkers‘ Evolution attempts to access a class mekanism.common.item.ItemHDPE$PlasticItem, which appears to be missing or have a different structure in the Mekanism Community Edition (CE) release.

This strongly suggests that Tinkers‘ Evolution was compiled against the API of the official Mekanism release, leading to a binary incompatibility with the CE version’s refactored codebase.

Steps to Reproduce
Set up a Minecraft 1.12.2 instance with Forge.

Install the following mods:

Mekanism-CE-Unofficial-All-9.9.2.237.jar (and its submodules)

tconevo-1.12.2-1.1.1.jar

Their required core mods (Mantle, Tinkers‘ Construct, etc.).

Launch the game.

Crash occurs immediately during the “Initializing game” phase.

Expected Behavior
The game should start successfully, and the integration between the two mods should initialize without error.

Actual Behavior
The game crashes with a java.lang.NoClassDefFoundError for the class mekanism.common.item.ItemHDPE$PlasticItem.

**Comment by zlf9790** [comment]
i solve it. Thank you for your continued work on maintaining Mekanism for 1.12.2.
