### ISSUE TITLE
java.lang.NoClassDefFoundError Crash with MEKCEU running on Cleanroom 0.6.8, works fine with 0.5.17

### ISSUE THREAD

**Issue by MatsuKari** [sddsd2332/Mekanism-CE-Unofficial-1.12.2#196]
Game crashes during startup phase when running mekceu at the latest version atm with Cleanroom 0.6.8.
Crash Logs (from different days as i tried to reproduce the crash at least a couple times):
Earliest: https://mclo.gs/wkM1Hhc
https://mclo.gs/TT3DIyH

Anything else you might need to fix this issue, just ask me and i'll provide it

**Comment by MatsuKari** [comment]
<img width="861" height="515" alt="Image" src="https://github.com/user-attachments/assets/6a49c152-d249-44b5-8f40-44c7eb439b8c" />
This happens when xaero is present in the pack, when it is taken off, it triggers the crash in the logs above

**Comment by sddsd2332** [comment]
This is not an error with mekceu, please visit this [issue](https://github.com/ACGaming/UniversalTweaks/issues/889) in Universal Tweaks to get a fix.

**Comment by sddsd2332** [comment]
> <img width="861" height="515" alt="Image" src="https://github.com/user-attachments/assets/6a49c152-d249-44b5-8f40-44c7eb439b8c" />
> This happens when xaero is present in the pack, when it is taken off, it triggers the crash in the logs above

This is not an issue with mekceu, it's because you haven't installed xaerolib
